#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2009, MARIMORE Inc Tokyo, Japan.
# Contributed by 
#       Iqbal Abdullah <iqbal@marimore.co.jp>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
#   *   Redistributions of source code must retain the above copyright notice, 
#       this list of conditions and the following disclaimer.
#   *   Redistributions in binary form must reproduce the above copyright notice, 
#       this list of conditions and the following disclaimer in the documentation 
#       and/or other materials provided with the distribution.
#   *   Neither the name of the MARIMORE Inc nor the names of its contributors 
#       may be used to endorse or promote products derived from this software 
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""
This module defines various general reusable data
"""

__author__      = "Iqbal Abdullah <iqbal@marimore.co.jp>"
__date__        = "$LastChangedDate: 2009-09-05 15:21:29 +0900 (土, 05  9月 2009) $"
__version__     = "$LastChangedRevision: 18 $"

WORLD_COUNTRIES = (

("AFGHANISTAN","AF"),
("ÅLAND ISLANDS","AX"),
("ALBANIA","AL"),
("ALGERIA","DZ"),
("AMERICAN SAMOA","AS"),
("ANDORRA","AD"),
("ANGOLA","AO"),
("ANGUILLA","AI"),
("ANTARCTICA","AQ"),
("ANTIGUA AND BARBUDA","AG"),
("ARGENTINA","AR"),
("ARMENIA","AM"),
("ARUBA","AW"),
("AUSTRALIA","AU"),
("AUSTRIA","AT"),
("AZERBAIJAN","AZ"),
("BAHAMAS","BS"),
("BAHRAIN","BH"),
("BANGLADESH","BD"),
("BARBADOS","BB"),
("BELARUS","BY"),
("BELGIUM","BE"),
("BELIZE","BZ"),
("BENIN","BJ"),
("BERMUDA","BM"),
("BHUTAN","BT"),
("BOLIVIA","BO"),
("BOSNIA AND HERZEGOVINA","BA"),
("BOTSWANA","BW"),
("BOUVET ISLAND","BV"),
("BRAZIL","BR"),
("BRITISH INDIAN OCEAN TERRITORY","IO"),
("BRUNEI DARUSSALAM","BN"),
("BULGARIA","BG"),
("BURKINA FASO","BF"),
("BURUNDI","BI"),
("CAMBODIA","KH"),
("CAMEROON","CM"),
("CANADA","CA"),
("CAPE VERDE","CV"),
("CAYMAN ISLANDS","KY"),
("CENTRAL AFRICAN REPUBLIC","CF"),
("CHAD","TD"),
("CHILE","CL"),
("CHINA","CN"),
("CHRISTMAS ISLAND","CX"),
("COCOS (KEELING) ISLANDS","CC"),
("COLOMBIA","CO"),
("COMOROS","KM"),
("CONGO","CG"),
("CONGO","CD"),
("COOK ISLANDS","CK"),
("COSTA RICA","CR"),
("CÔTE D'IVOIRE","CI"),
("CROATIA","HR"),
("CUBA","CU"),
("CYPRUS","CY"),
("CZECH REPUBLIC","CZ"),
("DENMARK","DK"),
("DJIBOUTI","DJ"),
("DOMINICA","DM"),
("DOMINICAN REPUBLIC","DO"),
("ECUADOR","EC"),
("EGYPT","EG"),
("EL SALVADOR","SV"),
("EQUATORIAL GUINEA","GQ"),
("ERITREA","ER"),
("ESTONIA","EE"),
("ETHIOPIA","ET"),
("FALKLAND ISLANDS (MALVINAS)","FK"),
("FAROE ISLANDS","FO"),
("FIJI","FJ"),
("FINLAND","FI"),
("FRANCE","FR"),
("FRENCH GUIANA","GF"),
("FRENCH POLYNESIA","PF"),
("FRENCH SOUTHERN TERRITORIES","TF"),
("GABON","GA"),
("GAMBIA","GM"),
("GEORGIA","GE"),
("GERMANY","DE"),
("GHANA","GH"),
("GIBRALTAR","GI"),
("GREECE","GR"),
("GREENLAND","GL"),
("GRENADA","GD"),
("GUADELOUPE","GP"),
("GUAM","GU"),
("GUATEMALA","GT"),
("GUERNSEY","GG"),
("GUINEA","GN"),
("GUINEA-BISSAU","GW"),
("GUYANA","GY"),
("HAITI","HT"),
("HEARD ISLAND AND MCDONALD ISLANDS","HM"),
("HOLY SEE (VATICAN CITY STATE)","VA"),
("HONDURAS","HN"),
("HONG KONG","HK"),
("HUNGARY","HU"),
("ICELAND","IS"),
("INDIA","IN"),
("INDONESIA","ID"),
("IRAN","IR"),
("IRAQ","IQ"),
("IRELAND","IE"),
("ISLE OF MAN","IM"),
("ISRAEL","IL"),
("ITALY","IT"),
("JAMAICA","JM"),
("JAPAN","JP"),
("JERSEY","JE"),
("JORDAN","JO"),
("KAZAKHSTAN","KZ"),
("KENYA","KE"),
("KIRIBATI","KI"),
("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","KP"),
("KOREA, REPUBLIC OF","KR"),
("KUWAIT","KW"),
("KYRGYZSTAN","KG"),
("LAO PEOPLE'S DEMOCRATIC REPUBLIC","LA"),
("LATVIA","LV"),
("LEBANON","LB"),
("LESOTHO","LS"),
("LIBERIA","LR"),
("LIBYAN ARAB JAMAHIRIYA","LY"),
("LIECHTENSTEIN","LI"),
("LITHUANIA","LT"),
("LUXEMBOURG","LU"),
("MACAO","MO"),
("MACEDONIA","MK"),
("MADAGASCAR","MG"),
("MALAWI","MW"),
("MALAYSIA","MY"),
("MALDIVES","MV"),
("MALI","ML"),
("MALTA","MT"),
("MARSHALL ISLANDS","MH"),
("MARTINIQUE","MQ"),
("MAURITANIA","MR"),
("MAURITIUS","MU"),
("MAYOTTE","YT"),
("MEXICO","MX"),
("MICRONESIA","FM"),
("MOLDOVA","MD"),
("MONACO","MC"),
("MONGOLIA","MN"),
("MONTENEGRO","ME"),
("MONTSERRAT","MS"),
("MOROCCO","MA"),
("MOZAMBIQUE","MZ"),
("MYANMAR","MM"),
("NAMIBIA","NA"),
("NAURU","NR"),
("NEPAL","NP"),
("NETHERLANDS","NL"),
("NETHERLANDS ANTILLES","AN"),
("NEW CALEDONIA","NC"),
("NEW ZEALAND","NZ"),
("NICARAGUA","NI"),
("NIGER","NE"),
("NIGERIA","NG"),
("NIUE","NU"),
("NORFOLK ISLAND","NF"),
("NORTHERN MARIANA ISLANDS","MP"),
("NORWAY","NO"),
("OMAN","OM"),
("PAKISTAN","PK"),
("PALAU","PW"),
("PALESTINIAN TERRITORY","PS"),
("PANAMA","PA"),
("PAPUA NEW GUINEA","PG"),
("PARAGUAY","PY"),
("PERU","PE"),
("PHILIPPINES","PH"),
("PITCAIRN","PN"),
("POLAND","PL"),
("PORTUGAL","PT"),
("PUERTO RICO","PR"),
("QATAR","QA"),
("REUNION","RE"),
("ROMANIA","RO"),
("RUSSIAN FEDERATION","RU"),
("RWANDA","RW"),
("SAINT BARTHÉLEMY","BL"),
("SAINT HELENA","SH"),
("SAINT KITTS AND NEVIS","KN"),
("SAINT LUCIA","LC"),
("SAINT MARTIN","MF"),
("SAINT PIERRE AND MIQUELON","PM"),
("SAINT VINCENT AND THE GRENADINES","VC"),
("SAMOA","WS"),
("SAN MARINO","SM"),
("SAO TOME AND PRINCIPE","ST"),
("SAUDI ARABIA","SA"),
("SENEGAL","SN"),
("SERBIA","RS"),
("SEYCHELLES","SC"),
("SIERRA LEONE","SL"),
("SINGAPORE","SG"),
("SLOVAKIA","SK"),
("SLOVENIA","SI"),
("SOLOMON ISLANDS","SB"),
("SOMALIA","SO"),
("SOUTH AFRICA","ZA"),
("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","GS"),
("SPAIN","ES"),
("SRI LANKA","LK"),
("SUDAN","SD"),
("SURINAME","SR"),
("SVALBARD AND JAN MAYEN","SJ"),
("SWAZILAND","SZ"),
("SWEDEN","SE"),
("SWITZERLAND","CH"),
("SYRIAN ARAB REPUBLIC","SY"),
("TAIWAN","TW"),
("TAJIKISTAN","TJ"),
("TANZANIA","TZ"),
("THAILAND","TH"),
("TIMOR-LESTE","TL"),
("TOGO","TG"),
("TOKELAU","TK"),
("TONGA","TO"),
("TRINIDAD AND TOBAGO","TT"),
("TUNISIA","TN"),
("TURKEY","TR"),
("TURKMENISTAN","TM"),
("TURKS AND CAICOS ISLANDS","TC"),
("TUVALU","TV"),
("UGANDA","UG"),
("UKRAINE","UA"),
("UNITED ARAB EMIRATES","AE"),
("UNITED KINGDOM","GB"),
("UNITED STATES","US"),
("UNITED STATES MINOR OUTLYING ISLANDS","UM"),
("URUGUAY","UY"),
("UZBEKISTAN","UZ"),
("VANUATU","VU"),
("VENEZUELA","VE"),
("VIET NAM","VN"),
("BRITISH VIRGIN ISLANDS","VG"),
("U.S VIRGIN ISLANDS","VI"),
("WALLIS AND FUTUNA","WF"),
("WESTERN SAHARA","EH"),
("YEMEN","YE"),
("ZAMBIA","ZM"),
("ZIMBABWE","ZW"),

)
